"""Create the final Task 1 report from actual post-run artifacts."""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs"


def fmt(value: str) -> str:
    try:
        return f"{float(value):.6f}"
    except (TypeError, ValueError):
        return str(value)


def repeated_4gram_rate(text: str) -> float:
    grams = [text[i:i + 4] for i in range(max(0, len(text) - 3))]
    return sum(1 for i, gram in enumerate(grams) if gram in grams[:i]) / max(1, len(grams))


def clean_snippet(text: str) -> str:
    return text.replace("`", "'").replace("\n", " ").strip()[:300]


metrics_path = OUT / "metrics.csv"
samples_path = OUT / "samples.json"
if not metrics_path.exists() or not samples_path.exists():
    raise FileNotFoundError("Run training first so outputs/metrics.csv and outputs/samples.json exist.")

with metrics_path.open(newline="") as stream:
    metrics = next(csv.DictReader(stream))
samples = json.loads(samples_path.read_text(encoding="utf-8"))

results = f"""# Task 1 results — Denisha Ketan Tank

## Model and training setup

This run trains a custom character-level GPT language model from scratch on TinyStories. It uses a 4-layer Transformer decoder with 4-head causal self-attention, `d_model=256`, head dimension 64, feed-forward dimension 1024, context length 128, learned token and position embeddings, pre-layer normalization, residual connections, GELU, dropout 0.1, AdamW, peak learning rate 0.0005, 500-step warm-up, cosine decay, gradient clipping at 1.0, and mixed precision on a Tesla T4.

The tokenizer is an explicit character vocabulary built from the selected stories. Training uses 100,000 stories and validation uses 10,000 stories with next-character cross-entropy.

## Final metrics

| Metric | Value |
|---|---:|
| Train cross-entropy | {fmt(metrics['train_loss'])} |
| Validation cross-entropy | {fmt(metrics['validation_loss'])} |
| Perplexity | {fmt(metrics['perplexity'])} |
| Bits per character | {fmt(metrics['bits_per_character'])} |
| Generalization gap | {fmt(metrics['generalization_gap'])} |
| Top-1 next-character accuracy | {fmt(metrics['top1_next_character_accuracy'])} |
| Distinct-1 / 2 / 3 | {fmt(metrics['distinct_1'])} / {fmt(metrics['distinct_2'])} / {fmt(metrics['distinct_3'])} |
| Repeated 4-gram rate | {fmt(metrics['repeated_4gram_rate'])} |
| Parameters | {metrics['parameter_count']} |
| Training tokens/sec | {fmt(metrics['training_tokens_per_second'])} |
| Generation tokens/sec | {fmt(metrics['generation_tokens_per_second'])} |
| Peak GPU memory (MB) | {fmt(metrics['peak_memory_mb'])} |
| Training time (seconds) | {fmt(metrics['training_time_seconds'])} |
| Device | {metrics['device']} |
| Vocabulary size | {metrics['vocabulary_size']} |
| Gradient NaN count | {metrics['gradient_nan_count']} |

## Interpretation

The validation loss and perplexity measure next-character prediction quality; lower is better. Top-1 accuracy measures how often the most likely predicted character matches the target. The generalization gap is validation loss minus training loss. The diversity metrics measure generated-text variety, while repeated 4-gram rate measures local repetition.
"""
(ROOT / "results.md").write_text(results, encoding="utf-8")

rows = []
for temperature, text in sorted(samples.items(), key=lambda item: float(item[0])):
    rate = repeated_4gram_rate(text)
    if rate >= 0.12:
        category = "Repetition"
        observation = f"The continuation has a relatively high repeated 4-character pattern rate ({rate:.3f}), suggesting local looping or overuse of common fragments."
        improvement = "Compare temperatures 0.7, 0.9, and 1.1; then test longer context or a repetition penalty and compare the repeated 4-gram rate."
    elif len(text.split()) < 35:
        category = "Fragmented coherence"
        observation = "The sample is short or contains few complete word boundaries, so the continuation is difficult to interpret as a coherent story."
        improvement = "Train for more completed epochs and compare this sample with a longer context window."
    else:
        category = "Grammar/coherence"
        observation = "The continuation is readable in places but still contains character-level spelling or sentence-boundary errors."
        improvement = "Compare decoding temperatures and evaluate longer generated continuations after additional training."
    rows.append((temperature, clean_snippet(text), category, observation, improvement))

failure = """# Task 1 sequence-model failure analysis

The cases below are copied from the actual `outputs/samples.json` generated by this run.

| Case | Temperature | Generated snippet | Failure type | Observation | Testable improvement |
|---|---:|---|---|---|---|
"""
for index, row in enumerate(rows, 1):
    failure += "| {} | {} | {} | {} | {} | {} |\n".format(index, *row)
(ROOT / "failure_analysis.md").write_text(failure, encoding="utf-8")
print("Wrote results.md and failure_analysis.md from the actual output artifacts.")
